### PR TITLE
Pin llvm-openmp=11 when building wheels for macOS

### LINKED ISSUE #628: Segmentation fault with TweedieDistribution log_likelihood
```python
import numpy as np
from glum._distribution import TweedieDistribution

td = TweedieDistribution(power=1.5)

td.log_likelihood(
    y=np.array([0.1, 0.2], dtype=float),
    mu=np.array([1, 2], dtype=float),
    dispersion=1.0,
)
```
Results in
```
segmentation fault  ipython
```

version:
Python 3.9.15
glum: 2.1.2
numpy: 1.23.5
MacOS 13.3, Intel Core i7

### PR DESCRIPTION
**Pull request by jtilly**
Closes #628.

I was able to reproduce the issue using the intel-based macOS runner: I'm building the wheel using `cibuildwheel` and then I'm installing the wheel and running the code snippet from the issue:

```yaml
jobs:
  macos:
    name: "issue-628"
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.13.0
        env:
          CIBW_ARCHS_MACOS: x86_64
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.15'
      - run: |
          pip install ./wheelhouse/*.whl
          python .github/workflows/issue_628.py
```

This [produces](https://github.com/Quantco/glum/actions/runs/5145139930/jobs/9262364272#step:5:63):
```
/Users/runner/work/_temp/d0cacb75-060f-4cd9-9f66-b7d751687330.sh: line 4:  6610 Segmentation fault: 11  python .github/workflows/issue_628.py
```

When I pin `llvm-openmp` to version 11 (like [scikit-learn](https://github.com/scikit-learn/scikit-learn/blob/ab7e3d19c16011d9ed4bd80f867336d8a741216a/build_tools/wheels/build_wheels.sh#L26)), everything runs through ([code](https://github.com/Quantco/glum/blob/0cd759d27256fee43bc4bb80d5252528c4ee25b7/.github/workflows/debug.yml), [output](https://github.com/Quantco/glum/actions/runs/5145588186/jobs/9263422129)).

### CODE REVIEW

**Comment by MarcAntoineSchmidtQC** [comment]
Amazing! Thanks Jan.

**Review by MarcAntoineSchmidtQC — APPROVED** [review]
Let's wait that the CI finishes but all good from my side.

**Comment by jtilly** [comment]
> The wheels are getting tested on the wheel-building architecture, but the problem happens when you install this on a different machine.

I was able to reproduce the issue on the _same_ machine. See https://github.com/Quantco/glum/actions/runs/5145139930/jobs/9262364272#step:5:63. We could add something along these lines to our CI pipeline. Build the wheels, install the wheels, run some code.

**Comment by jtilly** [comment]
Possibly related? https://github.com/dmlc/xgboost/issues/7039

**Pull request merged**
